apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.azure.platformref.crossplane.io
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platformref.crossplane.io/v1alpha1
    kind: XPostgreSQLInstance
  resources:
  - name: postgresqlserver
    base:
      apiVersion: database.azure.crossplane.io/v1beta1
      kind: PostgreSQLServer
      spec:
        forProvider:
          version: "11"
          administratorLogin: myadmin
          location: West US 2
          sslEnforcement: Disabled
          storageProfile:
              storageMB: 5120
          sku:
            tier: GeneralPurpose
            capacity: 2
            family: Gen5  
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-postgresql"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-postgresql"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: "spec.parameters.clusterRef.id"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
      - type: string
        string:
          fmt: "%s-postgresql"
    - fromFieldPath: "spec.parameters.storageGB"
      toFieldPath: "spec.forProvider.storageProfile.storageMB"
      transforms:
      - type: math
        math:
          multiply: 1024
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
    connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
  # db-server vnet-rule for subnet where AKS lives in
  - name: vnetrule
    base:
      apiVersion: database.azure.crossplane.io/v1alpha3
      kind: PostgreSQLServerVirtualNetworkRule
      spec:
        serverNameSelector:
          matchControllerRef: true
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-sn-rule"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
        - type: string
          string:
            fmt: "%s-sn-rule"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.properties.virtualNetworkSubnetIdSelector.matchLabels[azure.platformref.crossplane.io/app]
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]