apiVersion: azure.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure-nate
spec:
  id: platform-ref-azure-nate
  parameters:
    nodes:
      count: 1 #1-100
      size: small #small/medium/large
    services:
      operators:
        prometheus:
          version: "15.0.1"
  writeConnectionSecretToRef:
    name: platform-ref-azure-kubeconfig #Must be unique for each instance

