apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure.xsqlsrvs.db.platformref.crossplane.io
  labels:
    cloud: azure
spec:
  compositeTypeRef:
    apiVersion: db.platformref.crossplane.io/v1alpha1
    kind: XSQLSrv
  resources:
    - name: pwGenRelease 
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          providerConfigRef:
            name: in-cluster
          rollbackLimit: 0
          forProvider:
            skipCreateNamespace: true
            chart:
              url: https://raw.githubusercontent.com/upbound/platform-ref-tools/main/charts/secret-gen-0.1.0.tgz             
      patches:
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-db-srv-init-pw"
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.namespace
    - name: mariaDbServer
      base:
        apiVersion: dbformariadb.azure.upbound.io/v1beta1
        kind: Server
        spec:
          forProvider:
            version: "10.3"
            administratorLogin: myadmin
            administratorLoginPasswordSecretRef:
              key: password
            publicNetworkAccessEnabled: false
            location: East US 2
            sslEnforcement: Disabled
            skuName: "GP_Gen5_2"
            sslEnforcementEnabled: false
      patches:
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.namespace
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
          transforms:
          - type: string
            string:
              fmt: "%s-db-srv-init-pw"
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-mariadb" 
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
            - type: string
              string:
                fmt: "%s-mariadb"
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: "spec.parameters.clusterRef.id"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-mariadb"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.storageMb"
          transforms:
          - type: math
            math:
              multiply: 1024
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.dbResourceId
          policy:
            fromFieldPath: Required
      connectionDetails:
          - fromConnectionSecretKey: username
          - fromConnectionSecretKey: password
          - fromConnectionSecretKey: endpoint
          - fromConnectionSecretKey: port
    - name: prvtendpoint
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: PrivateEndpoint
        spec:
          forProvider:
            location: East US 2
            privateServiceConnection:
            - isManualConnection: false
              subresourceNames: ["mariadbServer"]
      patches:
        # - fromFieldPath: spec.parameters.clusterRef.id
        #   toFieldPath: metadata.name
        #   transforms:
          # - type: string
          #   string:
          #     fmt: "%s-prvtep"
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.privateServiceConnection[0].name
        - fromFieldPath: status.dbResourceId
          toFieldPath: spec.forProvider.privateServiceConnection[0].privateConnectionResourceId
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[azure.platformref.crossplane.io/app]
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.privateDnsZoneGroup[0].name
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.privateDnsZoneGroup[0].privateDnsZoneIdsSelector.matchLabels[azure.platformref.crossplane.io/app]


